import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { fileURLToPath, URL } from 'node:url'
import { readdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

// vite-ssg uses this same config for SSG build (via `vite-ssg build`).
// Per Кочегар+Дьюи+R1 memo: single-config approach preferred for consistency.

/**
 * kn.1 reader dynamic route prerender list — read chapter filesystem at build config time.
 * Reader restoration cont+30 S3SCOOP: /kn1/read/:slug needs static list для vite-ssg prerender.
 */
// Files к skip — Hugo internal section indices, not reader-facing chapters.
// Must match scripts/kn1-reader-manifest.mjs SKIP_FILES set.
const READER_SKIP_FILES = new Set(['_index.md', '_index.ru.md'])

/**
 * Enumerate kn.1 reader routes for given lang.
 * RU has no lang segment (backward compat); PT/EN prefixed с /kn1/{lang}/read/*.
 * Graceful: если lang dir absent OR empty — returns [] (silent skip).
 */
function kn1LangReaderRoutes(lang: string): string[] {
  const langSegment = lang === 'ru' ? '' : `/${lang}`
  const projectRoot = fileURLToPath(new URL('.', import.meta.url))
  const chaptersDir = resolve(projectRoot, `content/kn1/${lang}/chapters`)
  const routes: string[] = []
  try {
    for (const file of readdirSync(chaptersDir)) {
      if (!file.endsWith('.md') || READER_SKIP_FILES.has(file)) continue
      routes.push(`/kn1${langSegment}/read/${file.replace(/\.md$/, '')}`)
    }
    // Apparatus subfolder — optional (may not exist for PT/EN yet).
    const apparatusDir = resolve(chaptersDir, 'apparatus')
    try {
      for (const file of readdirSync(apparatusDir)) {
        if (!file.endsWith('.md') || READER_SKIP_FILES.has(file)) continue
        routes.push(`/kn1${langSegment}/read/apparatus-${file.replace(/\.md$/, '')}`)
      }
    } catch {
      // Apparatus dir absent — skip silently (PT/EN don't have apparatus yet).
    }
  } catch (err) {
    // Chapters dir absent — silent skip (EN scaffold pending).
    if (lang === 'ru') {
      console.warn(`[vite.config] Failed enumerate kn.1 chapters for ${lang}:`, err)
    }
  }
  return routes
}

function kn1ReaderRoutes(): string[] {
  // RU + PT + EN (order matters for prerender log clarity).
  return [
    ...kn1LangReaderRoutes('ru'),
    ...kn1LangReaderRoutes('pt'),
    ...kn1LangReaderRoutes('en'),
  ]
}

/**
 * kn.3 «Город Солнца» reader routes — generated by kn3-reader-manifest.mjs prebuild.
 * MASTER.md split by top-level # headings → chapters-generated/*.md.
 */
function kn3ReaderRoutes(): string[] {
  const chaptersDir = resolve(fileURLToPath(new URL('.', import.meta.url)), 'content/kn3/ru/chapters-generated')
  const routes: string[] = []
  try {
    for (const file of readdirSync(chaptersDir)) {
      if (!file.endsWith('.md')) continue
      routes.push(`/kn3/read/${file.replace(/\.md$/, '')}`)
    }
  } catch (err) {
    console.warn('[vite.config] Failed enumerate kn.3 chapters (prebuild may not have run):', err)
  }
  return routes
}

/**
 * kn.4 «Где живёт новое» reader routes — generated by kn4-reader-manifest.mjs prebuild.
 * Source content/kn4/ru/master.md (copied from vault Iskra S21 canonical).
 */
function kn4ReaderRoutes(): string[] {
  const chaptersDir = resolve(fileURLToPath(new URL('.', import.meta.url)), 'content/kn4/ru/chapters-generated')
  const routes: string[] = []
  try {
    for (const file of readdirSync(chaptersDir)) {
      if (!file.endsWith('.md')) continue
      routes.push(`/kn4/read/${file.replace(/\.md$/, '')}`)
    }
  } catch (err) {
    console.warn('[vite.config] Failed enumerate kn.4 chapters (prebuild may not have run):', err)
  }
  return routes
}

/**
 * kn.5 «Чужими руками» reader routes — generated by kn5-reader-manifest.mjs.
 * Source pandoc HTML→MD file, split by ::: {.section data-title="..."} markers.
 */
function kn5ReaderRoutes(): string[] {
  const chaptersDir = resolve(fileURLToPath(new URL('.', import.meta.url)), 'content/kn5/ru/chapters-generated')
  const routes: string[] = []
  try {
    for (const file of readdirSync(chaptersDir)) {
      if (!file.endsWith('.md')) continue
      routes.push(`/kn5/read/${file.replace(/\.md$/, '')}`)
    }
  } catch (err) {
    console.warn('[vite.config] Failed enumerate kn.5 chapters (prebuild may not have run):', err)
  }
  return routes
}

/**
 * kn.7 «Трудности диалога» reader routes — generated by kn7-reader-manifest.mjs.
 * Source content/kn7/ru/parts/*.md (17 separate files, no single MASTER.md).
 * Enumeration reads chapters-manifest.json directly (parts pattern не creates chapters-generated/).
 */
function kn7ReaderRoutes(): string[] {
  const manifestPath = resolve(fileURLToPath(new URL('.', import.meta.url)), 'content/kn7/ru/chapters-manifest.json')
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'))
    return manifest.entries.map((e: { slug: string }) => `/kn7/read/${e.slug}`)
  } catch (err) {
    console.warn('[vite.config] Failed enumerate kn.7 chapters (prebuild may not have run):', err)
    return []
  }
}

const KN1_RU_ROUTES = kn1LangReaderRoutes('ru')
const KN1_PT_ROUTES = kn1LangReaderRoutes('pt')
const KN1_EN_ROUTES = kn1LangReaderRoutes('en')
const KN1_READER_ROUTES = [...KN1_RU_ROUTES, ...KN1_PT_ROUTES, ...KN1_EN_ROUTES]
const KN3_READER_ROUTES = kn3ReaderRoutes()
const KN4_READER_ROUTES = kn4ReaderRoutes()
const KN5_READER_ROUTES = kn5ReaderRoutes()
const KN7_READER_ROUTES = kn7ReaderRoutes()
console.log(
  `[vite-ssg] Prerender kn.1 reader routes: ${KN1_READER_ROUTES.length}` +
  ` (ru: ${KN1_RU_ROUTES.length} + pt: ${KN1_PT_ROUTES.length} + en: ${KN1_EN_ROUTES.length})`,
)
console.log(`[vite-ssg] Prerender kn.3 reader routes: ${KN3_READER_ROUTES.length}`)
console.log(`[vite-ssg] Prerender kn.4 reader routes: ${KN4_READER_ROUTES.length}`)
console.log(`[vite-ssg] Prerender kn.5 reader routes: ${KN5_READER_ROUTES.length}`)
console.log(`[vite-ssg] Prerender kn.7 reader routes: ${KN7_READER_ROUTES.length}`)

export default defineConfig({
  plugins: [
    vue(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
      '@data': fileURLToPath(new URL('./data', import.meta.url)),
      '@content': fileURLToPath(new URL('./content', import.meta.url)),
    },
  },
  build: {
    // Bundle gate: 60KB gzip hard cap (per Дьюи Performance SEO + folkup-landing precedent)
    // Warning threshold triggers CI review
    chunkSizeWarningLimit: 60,
    // Rollup optimization
    rollupOptions: {
      output: {
        // manualChunks applied only in client build (SSR treats vue as external)
        manualChunks(id, { getModuleInfo }) {
          if (id.includes('node_modules')) {
            if (
              id.includes('/vue/') ||
              id.includes('/vue-router/') ||
              id.includes('/vue-i18n/') ||
              id.includes('/@unhead/')
            ) {
              // Only chunk into vendor for client build (getModuleInfo undefined in SSR external)
              return 'vendor'
            }
          }
        },
      },
    },
  },
  // SSG-specific settings (used by vite-ssg build)
  ssgOptions: {
    // Include static routes per page files
    formatting: 'minify',
    // Crawl all internal links
    crawl: true,
    // Explicit routes list — includes dynamic kn.1 reader routes (/kn1/read/:slug).
    // Static routes auto-discovered; dynamic ones must be enumerated explicitly.
    // Filter out route templates containing `:` (dynamic segments) — replaced
    // by concrete slug URLs. Per vite-ssg docs: https://github.com/antfu/vite-ssg#usage
    includedRoutes(paths: string[]) {
      const staticPaths = paths.filter((p) => !p.includes(':'))
      return [
        ...staticPaths,
        ...KN1_READER_ROUTES,
        ...KN3_READER_ROUTES,
        ...KN4_READER_ROUTES,
        ...KN5_READER_ROUTES,
        ...KN7_READER_ROUTES,
      ]
    },
    onFinished() {
      const readerCount =
        KN1_READER_ROUTES.length + KN3_READER_ROUTES.length +
        KN4_READER_ROUTES.length + KN5_READER_ROUTES.length + KN7_READER_ROUTES.length
      console.log(`vite-ssg build finished. Prerender includes ${readerCount} reader routes (kn.1: ${KN1_READER_ROUTES.length} + kn.3: ${KN3_READER_ROUTES.length} + kn.4: ${KN4_READER_ROUTES.length} + kn.5: ${KN5_READER_ROUTES.length} + kn.7: ${KN7_READER_ROUTES.length}). Verify sitemap.xml + hreflang links.`)
    },
  },
})
