// Auto-generated by scripts/kn5-reader-manifest.mjs — DO NOT EDIT.
// Pre-rendered HTML body для kn5 chapter. Loaded via dynamic import per-chunk.
// precommit:allow-ai-mentions
export default "<p>Кнуту ---\\<br>который, несмотря на языковой барьер\\<br>и разницу в возрасте, отнёсся ко мне\\<br>по-человечески</p>\n"
