// Auto-generated by scripts/kn5-reader-manifest.mjs — DO NOT EDIT.
// Pre-rendered HTML body для kn5 chapter. Loaded via dynamic import per-chunk.
// precommit:allow-ai-mentions
export default "<figure class=\"frontispiece\">  \n<img src=\"assets/ill-12-frontispiece.webp\" style=\"cursor:zoom-in;\" alt=\"Доберетный Че\" />  \n<figcaption>Доберетный Че — рисунок Ремедиос (ill-12)</figcaption>  \n</figure>\n"
