// Auto-generated by scripts/kn5-reader-manifest.mjs — DO NOT EDIT.
// Pre-rendered HTML body для kn5 chapter. Loaded via dynamic import per-chunk.
// precommit:allow-ai-mentions
export default "<p>Библиотека FolkUp · Трилогия «Из первых рук»  </p>\n<h1>Чужими руками</h1>\n<p>Об исторических посредниках  </p>\n<p>Команданте FolkUp</p>\n"
