// Auto-generated by scripts/kn3-reader-manifest.mjs — DO NOT EDIT.
// Pre-rendered HTML body для kn3 chapter. Loaded via dynamic import per-chunk.
// precommit:allow-ai-mentions
export default "<h2>Ретроспектива 2026</h2>\n<p><strong>Команданте FolkUp</strong></p>\n<hr>\n<blockquote>\n<p><em>«Когда мы отрешимся от себялюбия, у нас остаётся только любовь к общине».</em></p>\n<p>— Томмазо Кампанелла. «Город Солнца». Неаполитанская тюрьма, 1602</p>\n</blockquote>\n<blockquote>\n<p><em>«Лучшие архитектуры, требования и проекты возникают из самоорганизующихся команд».</em></p>\n<p>— Манифест гибкой разработки программного обеспечения, принцип 11. Сноубёрд, штат Юта, 2001</p>\n</blockquote>\n<hr>\n<p><em>Сетубал — Берлин, весна 2026 года</em></p>\n"
