/**
 * kn.3 «Город Солнца» chapters composable — manifest-driven TOC + lazy body loader.
 *
 * Bundle strategy (mirror kn.1 pattern per Lesson learned cont+30):
 *   - Manifest (metadata only, ~4 KB JSON) → eager import для TOC + navigation
 *   - Body content (~1.9 MB total 19 chapters) → non-eager glob, per-chunk lazy load
 *
 * Source: content/kn3/ru/chapters-generated/*.md (generated by kn3-reader-manifest.mjs
 * pre-build step из monolithic MASTER.md).
 */
import { ref } from 'vue'
import manifest from '../../content/kn3/ru/chapters-manifest.json'

// Lazy glob — each chapter separate chunk
const chapterBodyModules = import.meta.glob<string>(
  '../../content/kn3/ru/chapters-generated/*.md',
  { query: '?raw', import: 'default' },
)

export interface Kn3ChapterMeta {
  slug: string
  title: string
  description: string | null
  order: number
  isApparatus: boolean
}

interface Kn3Manifest {
  generated: string
  book: string
  locale: string
  entries: Kn3ChapterMeta[]
}

const typedManifest = manifest as Kn3Manifest

export function useKn3Chapters() {
  return ref(typedManifest.entries)
}

export function useKn3ChapterSlugs(): string[] {
  return typedManifest.entries.map((e) => e.slug)
}

export function useKn3ChapterMeta(slug: string) {
  const idx = typedManifest.entries.findIndex((e) => e.slug === slug)
  if (idx < 0) return { meta: null, prev: null, next: null }
  return {
    meta: typedManifest.entries[idx],
    prev: idx > 0 ? typedManifest.entries[idx - 1] : null,
    next:
      idx < typedManifest.entries.length - 1
        ? typedManifest.entries[idx + 1]
        : null,
  }
}

/**
 * Load chapter body (raw markdown с включённым H1 headingом).
 */
export async function loadKn3ChapterBody(slug: string): Promise<string | null> {
  const path = `../../content/kn3/ru/chapters-generated/${slug}.md`
  if (chapterBodyModules[path]) {
    return await chapterBodyModules[path]()
  }
  return null
}
