// Auto-generated by scripts/kn4-reader-manifest.mjs — DO NOT EDIT.
// Pre-rendered HTML body для kn4 chapter. Loaded via dynamic import per-chunk.
// precommit:allow-ai-mentions
export default "<p><em>Чистый читательский текст. Порядок чтения серии.</em></p>\n<hr>\n"
